### ISSUE TITLE
Computing the average is not correct

### ISSUE THREAD

**Issue by kolesnik** [kucherenko/caiman#1]
Suggested formula for adjusting AVG value 
<img width="418" alt="2016-11-12 12 29 31 pm" src="https://cloud.githubusercontent.com/assets/794450/20237173/c03e9a34-a8d3-11e6-8676-43aebc53db3c.png">

http://www.HostMath.com/Show.aspx?Code=m_%7Bn%7D%3D%5Cfrac%7Bm_%7Bn-1%7D(n-1)%20%2B%20x_%7Bn%7D%7D%7Bn%7D%3B%0A%0Afor%20%5B3%2C4%2C5%5D%20-%3E%5Cfrac%7B2%5Ctimes3.5%20%2B%205%7D%7B3%7D%3D4

**Comment by kucherenko** [comment]
fixed in caiman@0.1.2
